# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(316, 221)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.phpbutton = QtWidgets.QPushButton(self.page)
        self.phpbutton.setGeometry(QtCore.QRect(30, 40, 91, 61))
        self.phpbutton.setObjectName("phpbutton")
        self.aspbutton = QtWidgets.QPushButton(self.page)
        self.aspbutton.setGeometry(QtCore.QRect(140, 40, 91, 61))
        self.aspbutton.setObjectName("aspbutton")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 41))
        self.label.setObjectName("label")
        self.exitphpbutton = QtWidgets.QPushButton(self.page_2)
        self.exitphpbutton.setGeometry(QtCore.QRect(210, 20, 75, 23))
        self.exitphpbutton.setObjectName("exitphpbutton")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 81, 41))
        self.label_2.setObjectName("label_2")
        self.exitaspbutton = QtWidgets.QPushButton(self.page_3)
        self.exitaspbutton.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.exitaspbutton.setObjectName("exitaspbutton")
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 316, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.phpbutton.setText(_translate("MainWindow", "php"))
        self.aspbutton.setText(_translate("MainWindow", "asp"))
        self.label.setText(_translate("MainWindow", "Php Sayfası"))
        self.exitphpbutton.setText(_translate("MainWindow", "Anasafa"))
        self.label_2.setText(_translate("MainWindow", "Asp sayfası"))
        self.exitaspbutton.setText(_translate("MainWindow", "Anasafa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
